### ISSUE TITLE
wrong URL for an automated installation script

### ISSUE THREAD

**Issue by mkaddts** [docker/compose-switch#19]
It seems the wrong URL for an automated installation script:
"$ curl -fL https://raw.githubusercontent.com/docker/**compose-cli**/main/scripts/install/install_linux.sh | sh"
![image](https://user-images.githubusercontent.com/19425150/140677781-ce665308-2c1c-4c6c-a1d4-151b69969ba5.png)

**Comment by mat007** [comment]
Can you explain what problem you’re facing?

**Comment by mkaddts** [comment]
Yes! I'm not sure but your installation script (https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh) installs docker-cli - not 'compose-switch'.

**Comment by mat007** [comment]
Ah! Yes, good catch!

**Comment by mat007** [comment]
Opened #22 to fix it, thanks!
