### ISSUE TITLE
Failed at curl COMPOSE_SWITCH_URL

### ISSUE THREAD

**Issue by syyong** [docker/compose-switch#38]
Line 10 failed for me with "curl: (3) URL using bad/illegal format or missing URL". #37
`echo $COMPOSE_SWITCH_URL` returned:
/docker-compose-linux-amd64ompose-switch/releases/download/v1.0.5

When output it to a file and `cat -A`, I got:
https://github.com/docker/compose-switch/releases/download/v1.0.5^M/docker-compose-linux-amd64$

**Comment by nicksieger** [comment]
Sorry about that, thanks for reporting! Let me know if the fixes in #39 don't work for you.

**Comment by syyong** [comment]
Thanks for fixing this so quickly. That works.
